version: '3'

services:
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: somethingrandom
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
